apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      nodeSelector:
        ssdtype: slow
      containers:
        - image: mbps54/test-web-app:v5
          name: web-app
          imagePullPolicy: Always
          volumeMounts:
            - name: webapp-volume
              mountPath: /tmp
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 150m
              memory: 150Mi
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 1
            failureThreshold: 30
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 1
      volumes:
        - name: webapp-volume
          persistentVolumeClaim:
            claimName: webapp-pvc
            
